/*
 * The MIT License
 *
 * Copyright 2017 Denis Karev.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package dmk.ui;

import dmk.lang.*;
/**
 *
 * @author Денис
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        languagePanel = new javax.swing.JPanel();
        chooseFileLabel = new javax.swing.JLabel();
        chooseFileField = new javax.swing.JTextField();
        inputLabel = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();
        inField = new javax.swing.JTextField();
        outField = new javax.swing.JTextField();
        clearLabel = new javax.swing.JLabel();
        chooseField = new javax.swing.JTextField();
        crdLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        creditsField = new javax.swing.JTextField();
        exitField = new javax.swing.JTextField();
        tltipInpLabel = new javax.swing.JLabel();
        tltipInField = new javax.swing.JTextField();
        TltipOutLabel = new javax.swing.JLabel();
        tltipOutField = new javax.swing.JTextField();
        brdrInLabel = new javax.swing.JLabel();
        brdrOutLabel = new javax.swing.JLabel();
        brdrInField = new javax.swing.JTextField();
        brdrOutField = new javax.swing.JTextField();
        brdrMenuLabel = new javax.swing.JLabel();
        brdrLangLabel = new javax.swing.JLabel();
        brdrMnField = new javax.swing.JTextField();
        brdrLangField = new javax.swing.JTextField();
        settingsLabel = new javax.swing.JLabel();
        settingsField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        settingsLabel1 = new javax.swing.JLabel();
        settingsField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("imCurrJVM - Settings");

        languagePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(Translations.BORDER_LANGUAGE_TEXT));

        chooseFileLabel.setForeground(new java.awt.Color(0, 0, 204));
        chooseFileLabel.setText("CHOOSE_FILE");

        chooseFileField.setText("Choose file");

        inputLabel.setForeground(new java.awt.Color(0, 0, 204));
        inputLabel.setText("INPUT");

        outputLabel.setForeground(new java.awt.Color(0, 0, 204));
        outputLabel.setText("OUTPUT");

        inField.setText("Input");

        outField.setText("Output");

        clearLabel.setForeground(new java.awt.Color(0, 0, 204));
        clearLabel.setText("CLEAR");

        chooseField.setText("Clear");

        crdLabel.setForeground(new java.awt.Color(0, 0, 204));
        crdLabel.setText("CREDITS");

        exitLabel.setForeground(new java.awt.Color(0, 0, 204));
        exitLabel.setText("EXIT");

        creditsField.setText("Credits");

        exitField.setText("Exit");

        tltipInpLabel.setForeground(new java.awt.Color(0, 0, 204));
        tltipInpLabel.setText("TOOLTIP_INPUT_FIELD");

        tltipInField.setText("Input your text here!");

        TltipOutLabel.setForeground(new java.awt.Color(0, 0, 204));
        TltipOutLabel.setText("TOOLTIP_OUTPUT_FIELD");

        tltipOutField.setText("Output text will be here!");

        brdrInLabel.setForeground(new java.awt.Color(0, 0, 204));
        brdrInLabel.setText("BORDER_INPUT_TEXT");

        brdrOutLabel.setForeground(new java.awt.Color(0, 0, 204));
        brdrOutLabel.setText("BORDER_OUTPUT_TEXT");

        brdrInField.setText("Text input");

        brdrOutField.setText("Text output");

        brdrMenuLabel.setForeground(new java.awt.Color(0, 0, 204));
        brdrMenuLabel.setText("BORDER_MENU_TEXT");

        brdrLangLabel.setForeground(new java.awt.Color(0, 0, 204));
        brdrLangLabel.setText("BORDER_LANGUAGE_TEXT");

        brdrMnField.setText("Menu");

        brdrLangField.setText("Language settings");

        settingsLabel.setForeground(new java.awt.Color(0, 0, 204));
        settingsLabel.setText("SETTINGS");

        settingsField.setText("Settings");
        settingsField.setToolTipText("");

        saveButton.setText(Translations.SAVE);

        exitButton.setText(Translations.EXIT);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        settingsLabel1.setForeground(new java.awt.Color(0, 0, 204));
        settingsLabel1.setText("SAVE");

        settingsField1.setText("Save");
        settingsField1.setToolTipText("");

        javax.swing.GroupLayout languagePanelLayout = new javax.swing.GroupLayout(languagePanel);
        languagePanel.setLayout(languagePanelLayout);
        languagePanelLayout.setHorizontalGroup(
            languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(languagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chooseFileLabel)
                    .addComponent(inputLabel)
                    .addComponent(outputLabel)
                    .addComponent(clearLabel)
                    .addComponent(crdLabel)
                    .addComponent(exitLabel)
                    .addComponent(tltipInpLabel)
                    .addComponent(TltipOutLabel)
                    .addComponent(brdrOutLabel)
                    .addComponent(brdrInLabel)
                    .addComponent(brdrLangLabel)
                    .addComponent(brdrMenuLabel)
                    .addComponent(settingsLabel)
                    .addComponent(settingsLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brdrInField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(brdrOutField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(brdrMnField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(chooseFileField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(brdrLangField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(inField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chooseField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(settingsField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(settingsField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(creditsField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tltipInField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tltipOutField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, languagePanelLayout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton)
                .addGap(10, 10, 10))
        );
        languagePanelLayout.setVerticalGroup(
            languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(languagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseFileLabel)
                    .addComponent(chooseFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLabel)
                    .addComponent(inField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearLabel)
                    .addComponent(chooseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crdLabel)
                    .addComponent(creditsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitLabel)
                    .addComponent(exitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tltipInpLabel)
                    .addComponent(tltipInField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TltipOutLabel)
                    .addComponent(tltipOutField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brdrInLabel)
                    .addComponent(brdrInField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brdrOutLabel)
                    .addComponent(brdrOutField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brdrMenuLabel)
                    .addComponent(brdrMnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brdrLangLabel)
                    .addComponent(brdrLangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsLabel)
                    .addComponent(settingsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsLabel1)
                    .addComponent(settingsField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(exitButton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(languagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(languagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TltipOutLabel;
    private javax.swing.JTextField brdrInField;
    private javax.swing.JLabel brdrInLabel;
    private javax.swing.JTextField brdrLangField;
    private javax.swing.JLabel brdrLangLabel;
    private javax.swing.JLabel brdrMenuLabel;
    private javax.swing.JTextField brdrMnField;
    private javax.swing.JTextField brdrOutField;
    private javax.swing.JLabel brdrOutLabel;
    private javax.swing.JTextField chooseField;
    private javax.swing.JTextField chooseFileField;
    private javax.swing.JLabel chooseFileLabel;
    private javax.swing.JLabel clearLabel;
    private javax.swing.JLabel crdLabel;
    private javax.swing.JTextField creditsField;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField exitField;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JTextField inField;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JPanel languagePanel;
    private javax.swing.JTextField outField;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField settingsField;
    private javax.swing.JTextField settingsField1;
    private javax.swing.JLabel settingsLabel;
    private javax.swing.JLabel settingsLabel1;
    private javax.swing.JTextField tltipInField;
    private javax.swing.JLabel tltipInpLabel;
    private javax.swing.JTextField tltipOutField;
    // End of variables declaration//GEN-END:variables
}
